# Generated by Django 5.2.1 on 2025-06-02 10:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('github', models.URLField(blank=True)),
                ('github_icon', models.CharField(blank=True, default='fab fa-github', max_length=100)),
                ('github_color', models.CharField(blank=True, default='#333', max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('linkedin_icon', models.CharField(blank=True, default='fab fa-linkedin', max_length=100)),
                ('linkedin_color', models.CharField(blank=True, default='#0A66C2', max_length=20)),
                ('twitter', models.URLField(blank=True)),
                ('twitter_icon', models.CharField(blank=True, default='fab fa-twitter', max_length=100)),
                ('twitter_color', models.CharField(blank=True, default='#1DA1F2', max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('instagram_icon', models.CharField(blank=True, default='fab fa-instagram', max_length=100)),
                ('instagram_color', models.CharField(blank=True, default='#C13584', max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('facebook_icon', models.CharField(blank=True, default='fab fa-facebook-f', max_length=100)),
                ('facebook_color', models.CharField(blank=True, default='#1877F2', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('github_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('tech_stack', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.PositiveIntegerField(help_text='Skill level as a percentage (0-100)')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome class (e.g., 'fab fa-html5')", max_length=100)),
                ('icon_color', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
    ]
